#!/usr/bin/env bash
set -o errexit


print_stderr() {
	if [[ $1 == '0' ]]; then
		[[ $2 ]] && printf "$2" "${@:3}" 1>&2
	else
		[[ $2 ]] && printf '%s'"$2" "ERROR: ${0##*/}, " "${@:3}" 1>&2
		exit "$1"
	fi
}



remove_trailing_nl=
clear_after=
while [[ $1 ]]; do
	case $1 in
		'-r')
			remove_trailing_nl=1 ;;
		'-C'|'--clear-after')
			shift; clear_after=$1 ;;
		*)
			print_stderr 1 '%s\n' 'unrecognized parameter: '"$1" ;;
	esac
	shift
done



if [[ $clear_after ]]; then
	type clip-in clip-out md5sum sleep 1>/dev/null
	[[ $clear_after != *[^0123456789]* ]] || print_stderr 1 '%s %q\n' '--clear-after value not a whole number:' "$clear_after"
fi



# Check dependencies and define clipboard function based on environment
for _ in :; do
	# Wayland
	if [[ $WAYLAND_DISPLAY ]]; then
		type wl-copy 1>/dev/null
		clipboard() {
			wl-copy
		}
		break
	fi


	# Termux
	if [[ $SHELL == *'com.termux'* ]]; then
		type termux-clipboard-set 1>/dev/null
		clipboard() {
			termux-clipboard-set
		}
		break
	fi


	# X11
	if [[ $DISPLAY ]]; then
		if type xclip &> /dev/null; then
			clipboard() {
				xclip -selection clipboard -in
			}
			break
		fi

		if type xsel &> /dev/null; then
			clipboard() {
				xsel --clipboard --input
			}
			break
		fi

		print_stderr 1 'missing dependency: xsel or xclip'
	fi


	print_stderr 1 '%s\n' 'no eligible environment found'
done



if [[ $remove_trailing_nl ]]; then
	clipboard < <(tr -d '\n' < /dev/fd/0)
else
	clipboard < /dev/fd/0
fi



if [[ $clear_after ]]; then
	clipboard_sum_old=$(clip-out | md5sum)
	sleep -- "$clear_after"
	clipboard_sum_now=$(clip-out | md5sum)
	if [[ $clipboard_sum_now == "$clipboard_sum_old" ]]; then
		clip-in < <(printf '')
	fi
fi



