#!/usr/bin/env bash
set -o errexit


print_stderr() {
	if [[ $1 == '0' ]]; then
		[[ $2 ]] && printf "$2" "${@:3}" 1>&2
	else
		[[ $2 ]] && printf '%s'"$2" "ERROR: ${0##*/}, " "${@:3}" 1>&2
		exit "$1"
	fi
}



# Check dependencies and define clipboard function based on environment
for _ in :; do
	# Wayland
	if [[ $WAYLAND_DISPLAY ]]; then
		type wl-paste 1>/dev/null
		clipboard() {
			wl-paste
		}
		break
	fi


	# Termux
	if [[ $SHELL == *'com.termux'* ]]; then
		type termux-clipboard-get 1>/dev/null
		clipboard() {
			termux-clipboard-get
		}
		break
	fi


	# X11
	if [[ $DISPLAY ]]; then
		if type xclip &> /dev/null; then
			clipboard() {
				xclip -out -selection clipboard
			}
			break
		fi

		if type xsel &> /dev/null; then
			clipboard() {
				xsel --clipboard --output
			}
			break
		fi

		print_stderr 1 'missing dependency: xsel or xclip'
	fi


	print_stderr 1 '%s\n' 'no eligible environment found'
done



clipboard



